resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    all:
      vars:
        ansible_connection: ssh
        ansible_user: ubuntu
        folder_id: ${var.yandex_folder_id}
        service_account: ${yandex_iam_service_account.diplom.name}
        jenkins_user: admin
        newTokenName: diplom
        pipelineName: diplom
        pipelineXmlFile: ../terraform/config.xml
        cluster_id: ${yandex_kubernetes_cluster.netology_regional_cluster.id}
    jenkins_server:
      hosts:
        jenkins_server.netology.yc:
          ansible_host: ${yandex_compute_instance.jenkins_server.network_interface.0.nat_ip_address}
    DOC
    
  filename = "${path.module}/../ansible/inventory/prod/hosts.yml"
}