---
- hosts: "jenkins_server"
  tasks: 
  - name: Create key_diplom.json
    shell:
      cmd: |
        export PATH="$PATH:/home/$USER/yandex-cloud/bin"
        yc iam key create --service-account-name "{{ service_account }}" -o "/home/$USER/.config/yandex-cloud/key_diplom.json"
    delegate_to: 127.0.0.1
     
  - name: Set YC Jenkins profile and attach key_diplom.json to profile
    shell:
      cmd: |
        export PATH="$PATH:/home/$USER/yandex-cloud/bin"
        yc config profile create jenkins
        yc config set folder-id "{{ folder_id }}"
        yc config set service-account-key "/home/$USER/.config/yandex-cloud/key_diplom.json"
    delegate_to: 127.0.0.1

  - name: Attach YC config to Multibranch Pipeline
    command:
      argv:
      - curl
      - -X
      - POST
      - "http://{{ jenkins_user }}:{{ token.json.data.tokenValue }}@{{ address }}/job/{{ pipelineName }}/credentials/store/folder/domain/_/createCredentials"
      - -F 
      - "secret=@/home/$USER/.config/yandex-cloud/key_diplom.json"
      - -F
      - 'json={
          "": "4",
          "credentials": {
            "scope": "GLOBAL",
            "id": "keyjson",
            "file": "secret",
            "description": "keyjson",
            "stapler-class": "org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl",
            "$class": "org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl"
          }
        }'
      - -H
      - "Jenkins-Crumb:{{ crumb.json.crumb }}"
    delegate_to: 127.0.0.1
